
package org.janelia.it.jacs.model.download;
// Generated Oct 24, 2006 3:52:53 PM by Hibernate Tools 3.2.0.beta6a


import com.google.gwt.user.client.rpc.IsSerializable;
import org.janelia.it.jacs.model.metadata.Sample;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * DataFile generated by hbm2java
 */
public class DataFile implements Serializable, IsSerializable {

    // Fields

    private Long objectId;
    private String path;
    private String infoLocation;
    private String description;
    private long size;
    private boolean multifileArchive;
    private Set<Sample> samples = new HashSet<Sample>(0);

    // Constructors

    /**
     * default constructor
     */
    public DataFile() {
    }

    /**
     * full constructor
     *
     * @param path
     * @param infoLocation
     * @param description
     * @param size
     * @param multifileArchive
     * @param samples
     */
    public DataFile(String path, String infoLocation, String description, long size, boolean multifileArchive, Set<Sample> samples) {
        this.path = path;
        this.infoLocation = infoLocation;
        this.description = description;
        this.size = size;
        this.multifileArchive = multifileArchive;
        this.samples = samples;
    }


    // Property accessors
    public Long getObjectId() {
        return this.objectId;
    }

    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getInfoLocation() {
        return this.infoLocation;
    }

    public void setInfoLocation(String infoLocation) {
        this.infoLocation = infoLocation;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public long getSize() {
        return this.size;
    }

    public void setSize(long size) {
        this.size = size;
    }

    public boolean isMultifileArchive() {
        return this.multifileArchive;
    }

    public void setMultifileArchive(boolean multifileArchive) {
        this.multifileArchive = multifileArchive;
    }

    public Set<Sample> getSamples() {
        return this.samples;
    }

    public void setSamples(Set<Sample> samples) {
        this.samples = samples;
    }


}


