/*
 * Copyright (c) 2010-2011, J. Craig Venter Institute, Inc.
 *
 * This file is part of JCVI VICS.
 *
 * JCVI VICS is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the Artistic License 2.0.  For
 * details, see the full text of the license in the file LICENSE.txt.  No
 * other rights are granted.  Any and all third party software rights to
 * remain with the original developer.
 *
 * JCVI VICS is distributed in the hope that it will be useful in
 * bioinformatics applications, but it is provided "AS IS" and WITHOUT
 * ANY EXPRESS OR IMPLIED WARRANTIES including but not limited to
 * implied warranties of merchantability or fitness for any particular
 * purpose.  For details, see the full text of the license in the file
 * LICENSE.txt.
 *
 * You should have received a copy of the Artistic License 2.0 along with
 * JCVI VICS.  If not, the license can be obtained from
 * "http://www.perlfoundation.org/artistic_license_2_0."
 */

package org.janelia.it.jacs.model.download;
// Generated Oct 30, 2006 10:53:18 AM by Hibernate Tools 3.2.0.beta6a


import com.google.gwt.user.client.rpc.IsSerializable;

import java.util.ArrayList;
import java.util.List;

/**
 * HierarchyNode generated by hbm2java
 */
public class HierarchyNode implements java.io.Serializable, IsSerializable {

    // Fields

    private Long objectId;
    private String name;
    private String description;
    private List<DataFile> dataFiles = new ArrayList<DataFile>();
    private List<HierarchyNode> children = new ArrayList<HierarchyNode>();

    // Constructors

    /**
     * default constructor
     */
    public HierarchyNode() {
    }

    /**
     * full constructor
     */
    public HierarchyNode(String name, String description, List dataFiles, List children) {
        this.name = name;
        this.description = description;
        this.dataFiles = dataFiles;
        this.children = children;
    }


    // Property accessors
    public Long getObjectId() {
        return this.objectId;
    }

    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<DataFile> getDataFiles() {
        return this.dataFiles;
    }

    public void setDataFiles(List<DataFile> dataFiles) {
        this.dataFiles = dataFiles;
    }

    public List<HierarchyNode> getChildren() {
        return this.children;
    }

    public void setChildren(List<HierarchyNode> children) {
        this.children = children;
    }

}


