
package org.janelia.it.jacs.model.download;
// Generated Oct 30, 2006 10:53:18 AM by Hibernate Tools 3.2.0.beta6a


import com.google.gwt.user.client.rpc.IsSerializable;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Publication generated by hbm2java
 */
public class Publication implements Serializable, IsSerializable {

    // Fields

    private Long objectId;
    private String publicationAccession;
    private String abstractOfPublication;
    private String summary;
    private String title;
    private String subjectDocument;
    private List<Author> authors = new ArrayList<Author>();
    private List<DataFile> rolledUpArchives = new ArrayList<DataFile>();
    private List<HierarchyNode> hierarchyRootNodes = new ArrayList<HierarchyNode>();
    private String description;
    private String supplementalText;
    private Date pubDate;
    private String journalEntry;
    private List<Project> projects = new ArrayList<Project>();

    // Constructors

    /**
     * default constructor
     */
    public Publication() {
    }

    /**
     * full constructor
     */
    public Publication(String abstractOfPublication, String summary, String title, String subjectDocument,
                       List<Author> authors, List<DataFile> rolledUpArchives, List<HierarchyNode> hierarchyRootNodes) {
        this.abstractOfPublication = abstractOfPublication;
        this.summary = summary;
        this.title = title;
        this.subjectDocument = subjectDocument;
        this.authors = authors;
        this.rolledUpArchives = rolledUpArchives;
        this.hierarchyRootNodes = hierarchyRootNodes;
    }


    // Property accessors
    public Long getObjectId() {
        return this.objectId;
    }

    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    public String getAbstractOfPublication() {
        return this.abstractOfPublication;
    }

    public void setAbstractOfPublication(String abstractOfPublication) {
        this.abstractOfPublication = abstractOfPublication;
    }

    public String getSummary() {
        return this.summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSubjectDocument() {
        return this.subjectDocument;
    }

    public void setSubjectDocument(String subjectDocument) {
        this.subjectDocument = subjectDocument;
    }

    public List<Author> getAuthors() {
        return this.authors;
    }

    public void setAuthors(List<Author> authors) {
        this.authors = authors;
    }

    public List<DataFile> getRolledUpArchives() {
        return this.rolledUpArchives;
    }

    public void setRolledUpArchives(List<DataFile> rolledUpArchives) {
        this.rolledUpArchives = rolledUpArchives;
    }

    public List<HierarchyNode> getHierarchyRootNodes() {
        return this.hierarchyRootNodes;
    }

    public void setHierarchyRootNodes(List<HierarchyNode> hierarchyRootNodes) {
        this.hierarchyRootNodes = hierarchyRootNodes;
    }

    public String getDescription() {
        return description;
    }

    public String getSupplementalText() {
        return supplementalText;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setSupplementalText(String supplementalText) {
        this.supplementalText = supplementalText;
    }

    public Date getPubDate() {
        return pubDate;
    }

    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    public String getJournalEntry() {
        return journalEntry;
    }

    public void setJournalEntry(String journalEntry) {
        this.journalEntry = journalEntry;
    }

    public List<Project> getProjects() {
        return projects;
    }

    public void setProjects(List<Project> projects) {
        this.projects = projects;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null) return false;

        final Publication that = (Publication) o;

        if (that.getObjectId() != null && this.getObjectId() != null) {
            return that.getObjectId().equals(this.getObjectId());
        }

        return that.getTitle().equals(this.getTitle());
    }

    public int hashCode() {
        if (getObjectId() != null) {
            return getObjectId().hashCode();
        }
        else {
            return getTitle().hashCode();
        }
    }

    public String getPublicationAccession() {
        return publicationAccession;
    }

    public void setPublicationAccession(String publicationAccession) {
        this.publicationAccession = publicationAccession;
    }
}


