% program that reads a tiff file adds 11 by10 pixels to the images
% generated by the greeen camera so the images can be equal in dimension
% compared with the red channel
clear all
disp('Please select the folder which ONLY contains the raw image stack which is needed to be processed!!')
folder_name = uigetdir
%folder_name = 'C:\Users\labadmin\Desktop\Analysis\Output\Reconstruction\PSF beads3 07-26 cut by 07-26 mat'
files=dir(fullfile(folder_name,'*.tif'));
h = waitbar(0,'Start...');
for i=1:length(files)

imFilename=[folder_name '\' files(i).name];
outFolder= folder_name
%mkdir(outFolder,files(i).name(1:end-4))
%outFilename=[outFolder,'\',files(i).name(1:end-4),'\',files(i).name(1:end-4)]
outFilename=[outFolder,'\SCALED',files(i).name(1:end-4)]

%[FileName, PathName]=uigetfile('.tif', 'Select the Stack Image');
%imFilename=[PathName,FileName];
%outFilename=[PathName,FileName(1:end-4),'resized'];
 
info=imfinfo(imFilename);
numFrames=length(info);

for k=1:numFrames
        %A=imread('C:\Users\hajjb\Documents\Bassam folder\DATA_MULTI_FOCUS_MICROSCOPE\2011-11-04 NPC green and red\NPC-0.5um grating\MAX_3929green_Fri Nov 04 2011_11.41.02_002.tif');
        A=imread(imFilename,k);
        [m,n]=size(A);
        if m==501
            B=[zeros(512,5),[zeros(5,502);A;zeros(6,502)],zeros(512,5)];
        else 
            B=[zeros(512,5),[zeros(5,501);A;zeros(5,501)],zeros(512,6)];
        end
            imwrite(B,[outFilename,'.tif'], 'Compression', 'none', 'WriteMode', 'append');
end 


end
display('done')