//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.21 at 12:51:40 PM EST 
//


package org.janelia.it.jacs.shared.blast.blastxmlparser.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IterationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IterationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Iteration_iter-num" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Iteration_query-ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Iteration_query-def" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Iteration_query-len" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Iteration_hits" type="{}Hit" minOccurs="0"/>
 *         &lt;element name="Iteration_stat" type="{}Statistics" minOccurs="0"/>
 *         &lt;element name="Iteration_message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IterationType", propOrder = {
    "iterationIterNum",
    "iterationQueryID",
    "iterationQueryDef",
    "iterationQueryLen",
    "iterationHits",
    "iterationStat",
    "iterationMessage"
})
public class IterationType {

    @XmlElement(name = "Iteration_iter-num", required = true)
    protected BigInteger iterationIterNum;
    @XmlElement(name = "Iteration_query-ID")
    protected String iterationQueryID;
    @XmlElement(name = "Iteration_query-def")
    protected String iterationQueryDef;
    @XmlElement(name = "Iteration_query-len")
    protected BigInteger iterationQueryLen;
    @XmlElement(name = "Iteration_hits")
    protected Hit iterationHits;
    @XmlElement(name = "Iteration_stat")
    protected Statistics iterationStat;
    @XmlElement(name = "Iteration_message")
    protected String iterationMessage;

    /**
     * Gets the value of the iterationIterNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIterationIterNum() {
        return iterationIterNum;
    }

    /**
     * Sets the value of the iterationIterNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIterationIterNum(BigInteger value) {
        this.iterationIterNum = value;
    }

    /**
     * Gets the value of the iterationQueryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIterationQueryID() {
        return iterationQueryID;
    }

    /**
     * Sets the value of the iterationQueryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIterationQueryID(String value) {
        this.iterationQueryID = value;
    }

    /**
     * Gets the value of the iterationQueryDef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIterationQueryDef() {
        return iterationQueryDef;
    }

    /**
     * Sets the value of the iterationQueryDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIterationQueryDef(String value) {
        this.iterationQueryDef = value;
    }

    /**
     * Gets the value of the iterationQueryLen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIterationQueryLen() {
        return iterationQueryLen;
    }

    /**
     * Sets the value of the iterationQueryLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIterationQueryLen(BigInteger value) {
        this.iterationQueryLen = value;
    }

    /**
     * Gets the value of the iterationHits property.
     * 
     * @return
     *     possible object is
     *     {@link Hit }
     *     
     */
    public Hit getIterationHits() {
        return iterationHits;
    }

    /**
     * Sets the value of the iterationHits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hit }
     *     
     */
    public void setIterationHits(Hit value) {
        this.iterationHits = value;
    }

    /**
     * Gets the value of the iterationStat property.
     * 
     * @return
     *     possible object is
     *     {@link Statistics }
     *     
     */
    public Statistics getIterationStat() {
        return iterationStat;
    }

    /**
     * Sets the value of the iterationStat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statistics }
     *     
     */
    public void setIterationStat(Statistics value) {
        this.iterationStat = value;
    }

    /**
     * Gets the value of the iterationMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIterationMessage() {
        return iterationMessage;
    }

    /**
     * Sets the value of the iterationMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIterationMessage(String value) {
        this.iterationMessage = value;
    }

}
