//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.17 at 09:57:34 AM EST 
//


package org.janelia.it.jacs.shared.blast.blastxmlparser.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatisticsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatisticsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Statistics_db-num" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Statistics_db-len" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Statistics_hsp-len" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Statistics_eff-space" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Statistics_kappa" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Statistics_lambda" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Statistics_entropy" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatisticsType", propOrder = {
    "statisticsDbNum",
    "statisticsDbLen",
    "statisticsHspLen",
    "statisticsEffSpace",
    "statisticsKappa",
    "statisticsLambda",
    "statisticsEntropy"
})
public class StatisticsType {

    @XmlElement(name = "Statistics_db-num", required = true)
    protected BigInteger statisticsDbNum;
    @XmlElement(name = "Statistics_db-len", required = true)
    protected BigInteger statisticsDbLen;
    @XmlElement(name = "Statistics_hsp-len", required = true)
    protected BigInteger statisticsHspLen;
    @XmlElement(name = "Statistics_eff-space")
    protected float statisticsEffSpace;
    @XmlElement(name = "Statistics_kappa")
    protected float statisticsKappa;
    @XmlElement(name = "Statistics_lambda")
    protected float statisticsLambda;
    @XmlElement(name = "Statistics_entropy")
    protected float statisticsEntropy;

    /**
     * Gets the value of the statisticsDbNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatisticsDbNum() {
        return statisticsDbNum;
    }

    /**
     * Sets the value of the statisticsDbNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatisticsDbNum(BigInteger value) {
        this.statisticsDbNum = value;
    }

    /**
     * Gets the value of the statisticsDbLen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatisticsDbLen() {
        return statisticsDbLen;
    }

    /**
     * Sets the value of the statisticsDbLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatisticsDbLen(BigInteger value) {
        this.statisticsDbLen = value;
    }

    /**
     * Gets the value of the statisticsHspLen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatisticsHspLen() {
        return statisticsHspLen;
    }

    /**
     * Sets the value of the statisticsHspLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatisticsHspLen(BigInteger value) {
        this.statisticsHspLen = value;
    }

    /**
     * Gets the value of the statisticsEffSpace property.
     * 
     */
    public float getStatisticsEffSpace() {
        return statisticsEffSpace;
    }

    /**
     * Sets the value of the statisticsEffSpace property.
     * 
     */
    public void setStatisticsEffSpace(float value) {
        this.statisticsEffSpace = value;
    }

    /**
     * Gets the value of the statisticsKappa property.
     * 
     */
    public float getStatisticsKappa() {
        return statisticsKappa;
    }

    /**
     * Sets the value of the statisticsKappa property.
     * 
     */
    public void setStatisticsKappa(float value) {
        this.statisticsKappa = value;
    }

    /**
     * Gets the value of the statisticsLambda property.
     * 
     */
    public float getStatisticsLambda() {
        return statisticsLambda;
    }

    /**
     * Sets the value of the statisticsLambda property.
     * 
     */
    public void setStatisticsLambda(float value) {
        this.statisticsLambda = value;
    }

    /**
     * Gets the value of the statisticsEntropy property.
     * 
     */
    public float getStatisticsEntropy() {
        return statisticsEntropy;
    }

    /**
     * Sets the value of the statisticsEntropy property.
     * 
     */
    public void setStatisticsEntropy(float value) {
        this.statisticsEntropy = value;
    }

}
