
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 12:05:11 PM EDT 
//


package org.janelia.it.jacs.server.jaxb.reference_record;


/**
 * Java content class for file element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/current_projects/cvsfiles/Camera/shared/schema/reference_record.xsd line 96)
 * <p/>
 * <pre>
 * &lt;element name="file">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="info_path" type="{}file_path_type" />
 *         &lt;attribute name="path" use="required" type="{}file_path_type" />
 *         &lt;attribute name="size" type="{}nonZeroLong" />
 *         &lt;attribute name="tar" type="{}tar_type" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 */
public interface File
        extends javax.xml.bind.Element, org.janelia.it.jacs.server.jaxb.reference_record.FileType {


}
