
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 12:05:11 PM EDT 
//


package org.janelia.it.jacs.server.jaxb.reference_record;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.janelia.it.jacs.server.jaxb.reference_record package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
public class ObjectFactory
        extends org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.DefaultJAXBContextImpl {

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(19, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.GrammarInfo grammarInfo = new org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (org.janelia.it.jacs.server.jaxb.reference_record.ObjectFactory.class));
    public final static java.lang.Class version = (org.janelia.it.jacs.server.jaxb.reference_record.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.Subdir.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.SubdirImpl");
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.SubdirType.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.SubdirTypeImpl");
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl");
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.PublicationType.DateType.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl$PublicationTypeImpl$DateTypeImpl");
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.PublicationType.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl$PublicationTypeImpl");
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.PublicationType.JournalType.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl$PublicationTypeImpl$JournalTypeImpl");
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.File.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.FileImpl");
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.DataType.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl$DataTypeImpl");
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.FileType.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.FileTypeImpl");
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.AuthorsType.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl$AuthorsTypeImpl");
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecord.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordImpl");
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.TextType.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.TextTypeImpl");
        defaultImplementations.put((org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.CombinedDataType.class), "org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl$CombinedDataTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("", "subdir"), (org.janelia.it.jacs.server.jaxb.reference_record.Subdir.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "file"), (org.janelia.it.jacs.server.jaxb.reference_record.File.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "reference_record"), (org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecord.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.janelia.it.jacs.server.jaxb.reference_record
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     *
     * @param javaContentInterface the Class object of the javacontent interface to instantiate
     * @return a new instance
     * @throws JAXBException if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
            throws javax.xml.bind.JAXBException {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     *
     * @param name the name of the property to retrieve
     * @return the value of the requested property
     * @throws PropertyException when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
            throws javax.xml.bind.PropertyException {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     *
     * @param value the value of the property to be set
     * @param name  the name of the property to retrieve
     * @throws PropertyException when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
            throws javax.xml.bind.PropertyException {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of Subdir
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.Subdir createSubdir()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.SubdirImpl();
    }

    /**
     * Create an instance of SubdirType
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.SubdirType createSubdirType()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.SubdirTypeImpl();
    }

    /**
     * Create an instance of ReferenceRecordType
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType createReferenceRecordType()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl();
    }

    /**
     * Create an instance of ReferenceRecordTypePublicationTypeDateType
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.PublicationType.DateType createReferenceRecordTypePublicationTypeDateType()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl.PublicationTypeImpl.DateTypeImpl();
    }

    /**
     * Create an instance of ReferenceRecordTypePublicationType
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.PublicationType createReferenceRecordTypePublicationType()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl.PublicationTypeImpl();
    }

    /**
     * Create an instance of ReferenceRecordTypePublicationTypeJournalType
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.PublicationType.JournalType createReferenceRecordTypePublicationTypeJournalType()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl.PublicationTypeImpl.JournalTypeImpl();
    }

    /**
     * Create an instance of File
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.File createFile()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.FileImpl();
    }

    /**
     * Create an instance of ReferenceRecordTypeDataType
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.DataType createReferenceRecordTypeDataType()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl.DataTypeImpl();
    }

    /**
     * Create an instance of FileType
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.FileType createFileType()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.FileTypeImpl();
    }

    /**
     * Create an instance of ReferenceRecordTypeAuthorsType
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.AuthorsType createReferenceRecordTypeAuthorsType()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl.AuthorsTypeImpl();
    }

    /**
     * Create an instance of ReferenceRecord
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecord createReferenceRecord()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordImpl();
    }

    /**
     * Create an instance of TextType
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.TextType createTextType()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.TextTypeImpl();
    }

    /**
     * Create an instance of ReferenceRecordTypeCombinedDataType
     *
     * @throws JAXBException if an error occurs
     */
    public org.janelia.it.jacs.server.jaxb.reference_record.ReferenceRecordType.CombinedDataType createReferenceRecordTypeCombinedDataType()
            throws javax.xml.bind.JAXBException {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.ReferenceRecordTypeImpl.CombinedDataTypeImpl();
    }

}
