
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 12:05:11 PM EDT 
//


package org.janelia.it.jacs.server.jaxb.reference_record;


import java.lang.String;
import java.util.List;

/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/current_projects/cvsfiles/Camera/shared/schema/reference_record.xsd line 18)
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="authors">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="publication">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="date">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="day" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="month" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="year" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="journal">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="issue" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="page" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="volume" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="abstract" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="full_text" type="{}text_type"/>
 *         &lt;element name="supplemental_text" type="{}text_type"/>
 *         &lt;element name="combined_data" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}file" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element ref="{}subdir"/>
 *                   &lt;element ref="{}file"/>
 *                 &lt;/choice>
 *                 &lt;attribute name="path_prefix" use="required" type="{}path_prefix_type" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
public interface ReferenceRecordType {


    /**
     * Gets the value of the combinedData property.
     *
     * @return possible object is
     *         {@link ReferenceRecordType.CombinedDataType}
     */
    ReferenceRecordType.CombinedDataType getCombinedData();

    /**
     * Sets the value of the combinedData property.
     *
     * @param value allowed object is
     *              {@link ReferenceRecordType.CombinedDataType}
     */
    void setCombinedData(ReferenceRecordType.CombinedDataType value);

    /**
     * Gets the value of the data property.
     *
     * @return possible object is
     *         {@link ReferenceRecordType.DataType}
     */
    ReferenceRecordType.DataType getData();

    /**
     * Sets the value of the data property.
     *
     * @param value allowed object is
     *              {@link ReferenceRecordType.DataType}
     */
    void setData(ReferenceRecordType.DataType value);

    /**
     * Gets the value of the summary property.
     *
     * @return possible object is
     *         {@link String}
     */
    String getSummary();

    /**
     * Sets the value of the summary property.
     *
     * @param value allowed object is
     *              {@link String}
     */
    void setSummary(String value);

    /**
     * Gets the value of the publication property.
     *
     * @return possible object is
     *         {@link ReferenceRecordType.PublicationType}
     */
    ReferenceRecordType.PublicationType getPublication();

    /**
     * Sets the value of the publication property.
     *
     * @param value allowed object is
     *              {@link ReferenceRecordType.PublicationType}
     */
    void setPublication(ReferenceRecordType.PublicationType value);

    /**
     * Gets the value of the authors property.
     *
     * @return possible object is
     *         {@link ReferenceRecordType.AuthorsType}
     */
    ReferenceRecordType.AuthorsType getAuthors();

    /**
     * Sets the value of the authors property.
     *
     * @param value allowed object is
     *              {@link ReferenceRecordType.AuthorsType}
     */
    void setAuthors(ReferenceRecordType.AuthorsType value);

    /**
     * Gets the value of the fullText property.
     *
     * @return possible object is
     *         {@link TextType}
     */
    TextType getFullText();

    /**
     * Sets the value of the fullText property.
     *
     * @param value allowed object is
     *              {@link TextType}
     */
    void setFullText(TextType value);

    /**
     * Gets the value of the title property.
     *
     * @return possible object is
     *         {@link String}
     */
    String getTitle();

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is
     *              {@link String}
     */
    void setTitle(String value);

    /**
     * Gets the value of the abstract property.
     *
     * @return possible object is
     *         {@link String}
     */
    String getAbstract();

    /**
     * Sets the value of the abstract property.
     *
     * @param value allowed object is
     *              {@link String}
     */
    void setAbstract(String value);

    /**
     * Gets the value of the supplementalText property.
     *
     * @return possible object is
     *         {@link TextType}
     */
    TextType getSupplementalText();

    /**
     * Sets the value of the supplementalText property.
     *
     * @param value allowed object is
     *              {@link TextType}
     */
    void setSupplementalText(TextType value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/current_projects/cvsfiles/Camera/shared/schema/reference_record.xsd line 24)
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public interface AuthorsType {


        /**
         * Gets the value of the Name property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the Name property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getName().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link String}
         */
        List getName();

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/current_projects/cvsfiles/Camera/shared/schema/reference_record.xsd line 71)
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}file" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public interface CombinedDataType {


        /**
         * Gets the value of the file property.
         *
         * @return possible object is
         *         {@link FileType}
         *         {@link org.janelia.it.jacs.server.jaxb.reference_record.File}
         */
        FileType getFile();

        /**
         * Sets the value of the file property.
         *
         * @param value allowed object is
         *              {@link FileType}
         *              {@link org.janelia.it.jacs.server.jaxb.reference_record.File}
         */
        void setFile(FileType value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/current_projects/cvsfiles/Camera/shared/schema/reference_record.xsd line 79)
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element ref="{}subdir"/>
     *         &lt;element ref="{}file"/>
     *       &lt;/choice>
     *       &lt;attribute name="path_prefix" use="required" type="{}path_prefix_type" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public interface DataType {


        /**
         * Gets the value of the pathPrefix property.
         *
         * @return possible object is
         *         {@link String}
         */
        String getPathPrefix();

        /**
         * Sets the value of the pathPrefix property.
         *
         * @param value allowed object is
         *              {@link String}
         */
        void setPathPrefix(String value);

        /**
         * Gets the value of the SubdirOrFile property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the SubdirOrFile property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubdirOrFile().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link org.janelia.it.jacs.server.jaxb.reference_record.Subdir}
         * {@link org.janelia.it.jacs.server.jaxb.reference_record.File}
         */
        List getSubdirOrFile();

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/current_projects/cvsfiles/Camera/shared/schema/reference_record.xsd line 32)
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="date">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="day" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="month" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="year" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="journal">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="issue" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="page" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="volume" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public interface PublicationType {


        /**
         * Gets the value of the journal property.
         *
         * @return possible object is
         *         {@link ReferenceRecordType.PublicationType.JournalType}
         */
        ReferenceRecordType.PublicationType.JournalType getJournal();

        /**
         * Sets the value of the journal property.
         *
         * @param value allowed object is
         *              {@link ReferenceRecordType.PublicationType.JournalType}
         */
        void setJournal(ReferenceRecordType.PublicationType.JournalType value);

        /**
         * Gets the value of the date property.
         *
         * @return possible object is
         *         {@link ReferenceRecordType.PublicationType.DateType}
         */
        ReferenceRecordType.PublicationType.DateType getDate();

        /**
         * Sets the value of the date property.
         *
         * @param value allowed object is
         *              {@link ReferenceRecordType.PublicationType.DateType}
         */
        void setDate(ReferenceRecordType.PublicationType.DateType value);


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/current_projects/cvsfiles/Camera/shared/schema/reference_record.xsd line 36)
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="day" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="month" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="year" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        public interface DateType {


            /**
             * Gets the value of the day property.
             *
             * @return possible object is
             *         {@link String}
             */
            String getDay();

            /**
             * Sets the value of the day property.
             *
             * @param value allowed object is
             *              {@link String}
             */
            void setDay(String value);

            /**
             * Gets the value of the year property.
             *
             * @return possible object is
             *         {@link String}
             */
            String getYear();

            /**
             * Sets the value of the year property.
             *
             * @param value allowed object is
             *              {@link String}
             */
            void setYear(String value);

            /**
             * Gets the value of the month property.
             *
             * @return possible object is
             *         {@link String}
             */
            String getMonth();

            /**
             * Sets the value of the month property.
             *
             * @param value allowed object is
             *              {@link String}
             */
            void setMonth(String value);

        }


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/current_projects/cvsfiles/Camera/shared/schema/reference_record.xsd line 47)
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="issue" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="page" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="volume" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        public interface JournalType {


            /**
             * Gets the value of the issue property.
             *
             * @return possible object is
             *         {@link String}
             */
            String getIssue();

            /**
             * Sets the value of the issue property.
             *
             * @param value allowed object is
             *              {@link String}
             */
            void setIssue(String value);

            /**
             * Gets the value of the volume property.
             *
             * @return possible object is
             *         {@link String}
             */
            String getVolume();

            /**
             * Sets the value of the volume property.
             *
             * @param value allowed object is
             *              {@link String}
             */
            void setVolume(String value);

            /**
             * Gets the value of the name property.
             *
             * @return possible object is
             *         {@link String}
             */
            String getName();

            /**
             * Sets the value of the name property.
             *
             * @param value allowed object is
             *              {@link String}
             */
            void setName(String value);

            /**
             * Gets the value of the page property.
             *
             * @return possible object is
             *         {@link String}
             */
            String getPage();

            /**
             * Sets the value of the page property.
             *
             * @param value allowed object is
             *              {@link String}
             */
            void setPage(String value);

        }

    }

}
