
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 12:05:11 PM EDT 
//


package org.janelia.it.jacs.server.jaxb.reference_record;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/current_projects/cvsfiles/Camera/shared/schema/reference_record.xsd line 107)
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}file"/>
 *         &lt;element ref="{}subdir"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{}dir_name_type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
public interface SubdirType {


    /**
     * Gets the value of the FileOrSubdir property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the FileOrSubdir property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileOrSubdir().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link org.janelia.it.jacs.server.jaxb.reference_record.Subdir}
     * {@link org.janelia.it.jacs.server.jaxb.reference_record.File}
     */
    java.util.List getFileOrSubdir();

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link java.lang.String}
     */
    java.lang.String getName();

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link java.lang.String}
     */
    void setName(java.lang.String value);

}
