
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:08 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.27 at 12:05:11 PM EDT 
//


package org.janelia.it.jacs.server.jaxb.reference_record.impl;

public class FileImpl
        extends org.janelia.it.jacs.server.jaxb.reference_record.impl.FileTypeImpl
        implements org.janelia.it.jacs.server.jaxb.reference_record.File, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.UnmarshallableObject, org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.XMLSerializable, org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.ValidatableObject {

    public final static java.lang.Class version = (org.janelia.it.jacs.server.jaxb.reference_record.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.janelia.it.jacs.server.jaxb.reference_record.File.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "file";
    }

    public org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.UnmarshallingContext context) {
        return new org.janelia.it.jacs.server.jaxb.reference_record.impl.FileImpl.Unmarshaller(context);
    }

    public void serializeBody(org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException {
        context.startElement("", "file");
        super.serializeURIs(context);
        context.endNamespaceDecls();
        super.serializeAttributes(context);
        context.endAttributes();
        super.serializeBody(context);
        context.endElement();
    }

    public void serializeAttributes(org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException {
    }

    public void serializeURIs(org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.XMLSerializer context)
            throws org.xml.sax.SAXException {
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.janelia.it.jacs.server.jaxb.reference_record.File.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
                    "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
                            + "\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
                            + "grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
                            + "\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
                            + "msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Lj"
                            + "ava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xppp\u0000sr\u0000\u001fcom.sun.msv.gra"
                            + "mmar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp"
                            + "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~\u0000\u0004ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007pps"
                            + "q\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
                            + "\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004ppsr\u0000\u001bcom.sun.msv.gramma"
                            + "r.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L"
                            + "\u0000\u0006exceptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0004pp"
                            + "sr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlway"
                            + "sValidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
                            + "\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'c"
                            + "om.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespac"
                            + "eUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000\u0018L\u0000\nwhiteSpacet\u0000.Lco"
                            + "m/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w"
                            + "3.org/2001/XMLSchemat\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd.Wh"
                            + "iteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatyp"
                            + "e.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.gramm"
                            + "ar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004ppsr\u0000\u001bcom.su"
                            + "n.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0018L\u0000\fnamespac"
                            + "eURIq\u0000~\u0000\u0018xpq\u0000~\u0000\u001cq\u0000~\u0000\u001bsr\u0000#com.sun.msv.grammar.SimpleNameClass"
                            + "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0018L\u0000\fnamespaceURIq\u0000~\u0000\u0018xr\u0000\u001dcom.sun."
                            + "msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u000bdescriptiont\u0000\u0000sr\u0000\u001dcom.s"
                            + "un.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\bppsq\u0000~\u0000\u000esr\u0000\u0011java.la"
                            + "ng.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u0010ppsr\u0000%com.sun.msv.dat"
                            + "atype.xsd.PatternFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001[\u0000\bpatternst\u0000\u0013[Ljava/lang/S"
                            + "tring;xr\u0000;com.sun.msv.datatype.xsd.DataTypeWithLexicalConstr"
                            + "aintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.DataTypeWit"
                            + "hFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueCheckFlagL\u0000\bbase"
                            + "Typet\u0000)Lcom/sun/msv/datatype/xsd/XSDatatypeImpl;L\u0000\fconcreteT"
                            + "ypet\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~"
                            + "\u0000\u0018xq\u0000~\u0000\u0017q\u0000~\u0000(t\u0000\u000efile_path_typeq\u0000~\u0000\u001f\u0000\u0000q\u0000~\u0000\u001aq\u0000~\u0000\u001at\u0000\u0007patternur\u0000"
                            + "\u0013[Ljava.lang.String;\u00ad\u00d2V\u00e7\u00e9\u001d{G\u0002\u0000\u0000xp\u0000\u0000\u0000\u0001t\u0000\u0012[A-Za-z0-9_\\-\\./]*q\u0000"
                            + "~\u0000!sq\u0000~\u0000\"q\u0000~\u00006q\u0000~\u0000(sq\u0000~\u0000$t\u0000\tinfo_pathq\u0000~\u0000(sr\u00000com.sun.msv.gr"
                            + "ammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004sq\u0000~\u0000,\u0001q\u0000"
                            + "~\u0000?sq\u0000~\u0000\u000eppq\u0000~\u0000.sq\u0000~\u0000$t\u0000\u0004pathq\u0000~\u0000(sq\u0000~\u0000)ppsq\u0000~\u0000\u000eq\u0000~\u0000-psq\u0000~\u0000\u0010"
                            + "ppsr\u0000*com.sun.msv.datatype.xsd.MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
                            + "r\u0000#com.sun.msv.datatype.xsd.RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitVal"
                            + "uet\u0000\u0012Ljava/lang/Object;xr\u00009com.sun.msv.datatype.xsd.DataType"
                            + "WithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xq\u0000~\u00002q\u0000~\u0000(t\u0000\u000bnonZeroLong"
                            + "sr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000"
                            + "\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001e\u0000\u0000sr\u0000!com.sun.msv.datatype.xsd.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
                            + "\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv.datatype.xsd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002"
                            + "\u0000\u0001L\u0000\nbaseFacetsq\u0000~\u00003xq\u0000~\u0000\u0015q\u0000~\u0000\u001bt\u0000\u0004longq\u0000~\u0000Nsr\u0000*com.sun.msv.d"
                            + "atatype.xsd.MaxInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Hppq\u0000~\u0000N\u0000\u0001sq\u0000~\u0000"
                            + "Gppq\u0000~\u0000N\u0000\u0000sr\u0000$com.sun.msv.datatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
                            + "\u0000xq\u0000~\u0000Pq\u0000~\u0000\u001bt\u0000\u0007integerq\u0000~\u0000Nsr\u0000,com.sun.msv.datatype.xsd.Frac"
                            + "tionDigitsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexq\u0000~\u00001ppq\u0000~\u0000N\u0001\u0000sr\u0000#com.sun"
                            + ".msv.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0015q\u0000~\u0000\u001bt\u0000\u0007decimal"
                            + "q\u0000~\u0000Nq\u0000~\u0000\\t\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u0000Wt\u0000\fminInclusivesr\u0000\u000ejava."
                            + "lang.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000x"
                            + "p\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u0000Wt\u0000\fmaxInclusivesq\u0000~\u0000`\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000Qq\u0000~\u0000_sq\u0000~\u0000`\u0000"
                            + "\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u0000!sq\u0000~\u0000\"q\u0000~\u0000Lq\u0000~\u0000(sq\u0000~\u0000$t\u0000\u0004sizeq\u0000~\u0000(q\u0000~\u0000?sq\u0000~\u0000)pps"
                            + "q\u0000~\u0000\u000eq\u0000~\u0000-psq\u0000~\u0000\u0010ppsq\u0000~\u0000Sq\u0000~\u0000(t\u0000\btar_typeq\u0000~\u0000N\u0000\u0001sq\u0000~\u0000Gq\u0000~\u0000(q"
                            + "\u0000~\u0000mq\u0000~\u0000N\u0000\u0000sr\u0000 com.sun.msv.datatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq"
                            + "\u0000~\u0000Pq\u0000~\u0000\u001bt\u0000\u0003intq\u0000~\u0000Nsq\u0000~\u0000Sppq\u0000~\u0000N\u0000\u0001sq\u0000~\u0000Gppq\u0000~\u0000N\u0000\u0000q\u0000~\u0000Qq\u0000~\u0000Q"
                            + "q\u0000~\u0000_sr\u0000\u0011java.lang.Integer\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u0000a\u0080\u0000\u0000\u0000q\u0000~\u0000Q"
                            + "q\u0000~\u0000csq\u0000~\u0000t\u007f\u00ff\u00ff\u00ffq\u0000~\u0000pq\u0000~\u0000_sq\u0000~\u0000t\u0000\u0000\u0000\u0000q\u0000~\u0000pq\u0000~\u0000csq\u0000~\u0000t\u0000\u0000\u0000\u0001q\u0000~\u0000!"
                            + "sq\u0000~\u0000\"q\u0000~\u0000mq\u0000~\u0000(sq\u0000~\u0000$t\u0000\u0003tarq\u0000~\u0000(q\u0000~\u0000?sq\u0000~\u0000)ppsq\u0000~\u0000\u000eq\u0000~\u0000-psq"
                            + "\u0000~\u0000\u0010ppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000"
                            + "\u0015q\u0000~\u0000\u001bt\u0000\u0005QNameq\u0000~\u0000Nq\u0000~\u0000!sq\u0000~\u0000\"q\u0000~\u0000\u0081q\u0000~\u0000\u001bsq\u0000~\u0000$t\u0000\u0004typet\u0000)http"
                            + "://www.w3.org/2001/XMLSchema-instanceq\u0000~\u0000?sq\u0000~\u0000$t\u0000\u0004fileq\u0000~\u0000("
                            + "sr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTable"
                            + "t\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com."
                            + "sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005count"
                            + "B\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionP"
                            + "ool;xp\u0000\u0000\u0000\t\u0001pq\u0000~\u0000\fq\u0000~\u0000\u000bq\u0000~\u0000\nq\u0000~\u0000\tq\u0000~\u0000Dq\u0000~\u0000\rq\u0000~\u0000*q\u0000~\u0000|q\u0000~\u0000ix"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
            extends org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.AbstractUnmarshallingEventHandlerImpl {


        public Unmarshaller(org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(org.janelia.it.jacs.server.jaxb.reference_record.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.janelia.it.jacs.server.jaxb.reference_record.impl.FileImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
                throws org.xml.sax.SAXException {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case 0:
                        if (("file" == ___local) && ("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return;
                        }
                        break;
                    case 1:
                        attIdx = context.getAttribute("", "description");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return;
                        }
                        break;
                    case 3:
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case 1:
                        attIdx = context.getAttribute("", "description");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return;
                        }
                        break;
                    case 3:
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return;
                    case 2:
                        if (("file" == ___local) && ("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case 1:
                        if (("description" == ___local) && ("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((org.janelia.it.jacs.server.jaxb.reference_record.impl.FileTypeImpl) org.janelia.it.jacs.server.jaxb.reference_record.impl.FileImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return;
                        }
                        break;
                    case 3:
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
                throws org.xml.sax.SAXException {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case 1:
                        attIdx = context.getAttribute("", "description");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return;
                        }
                        break;
                    case 3:
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
                throws org.xml.sax.SAXException {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case 1:
                            attIdx = context.getAttribute("", "description");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return;
                            }
                            break;
                        case 3:
                            revertToParentFromText(value);
                            return;
                    }
                }
                catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
