
package org.janelia.it.jacs.model.user_data;

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;

import com.google.gwt.user.client.rpc.IsSerializable;

/**
 * User generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.NONE)
public class User extends Subject implements java.io.Serializable, IsSerializable // NOT IsSerializable
{
    public static final String SYSTEM_USER_LOGIN = "system";
    public static final String SYSTEM_USER_KEY = "user:system";

    transient private boolean administrator = false;

    private Set<SubjectRelationship> groupRelationships = new HashSet<SubjectRelationship>(0);

    public User() {
    }

    /**
     * full constructor
     *
     * @param userLogin - username
     * @param name      - user's full name
     * @param nodes     - nodes for this user
     * @param tasks     - tasks associated with this user
     */
    public User(String userLogin, String name) {
    	super(userLogin, name, "user:"+name);
    }
    
    @Override
    public void setName(String name) {
		super.setName(name);
		setKey("user:"+name);
	}
    
    @Deprecated
    public String getUserLogin() {
        return getName();
    }

    @Deprecated
    public void setUserLogin(String userLogin) {
        setName(userLogin);
    }
    
    @Deprecated
    public Long getUserId() {
        return getId();
    }

    @Deprecated
    public void setUserId(Long userId) {
        setId(userId);
    }

    public Set<SubjectRelationship> getGroupRelationships() {
		return groupRelationships;
	}

	public void setGroupRelationships(Set<SubjectRelationship> groupRelationships) {
		this.groupRelationships = groupRelationships;
	}

    public boolean isAdministrator() {
        return administrator;
    }

    public void setAdministrator(boolean administrator) {
        this.administrator = administrator;
    }
}