function trans =dat2mat3d_v1(im)
% Extracts intensity values from stack and saves it in 3d Matrix

% trans ... Structure with  
% im    ... structure with image data (generated by tiffread)

nFrames = size(im,2);
width   = im(1).width;
height  = im(1).height;

%- 3d Matrix with intensity values
trans.data = zeros(height,width,nFrames);
for i=1:nFrames
    trans.data(:,:,i)=im(i).data;
end

trans.w    = width;
trans.h    = height;
trans.size = nFrames;


