package org.janelia.it.jacs.model.sage;

// Generated Oct 9, 2015 2:22:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Observation generated by hbm2java
 */
public class Observation implements java.io.Serializable {

    private Integer id;
    private CvTerm type;
    private Session session;
    private CvTerm term;
    private Integer experimentId;
    private String value;
    private Date createDate;

    public Observation() {
    }

    public Observation(CvTerm type, CvTerm term, String value, Date createDate) {
        this.type = type;
        this.term = term;
        this.value = value;
        this.createDate = createDate;
    }

    public Observation(CvTerm type, Session session, CvTerm term, Integer experimentId, String value, Date createDate) {
        this.type = type;
        this.session = session;
        this.term = term;
        this.experimentId = experimentId;
        this.value = value;
        this.createDate = createDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public CvTerm getType() {
        return this.type;
    }

    public void setType(CvTerm type) {
        this.type = type;
    }

    public Session getSession() {
        return this.session;
    }

    public void setSession(Session session) {
        this.session = session;
    }

    public CvTerm getTerm() {
        return this.term;
    }

    public void setTerm(CvTerm term) {
        this.term = term;
    }

    public Integer getExperimentId() {
        return this.experimentId;
    }

    public void setExperimentId(Integer experimentId) {
        this.experimentId = experimentId;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

}
