package org.janelia.it.jacs.model.entity;
// Generated May 26, 2011 10:42:23 AM by Hibernate Tools 3.2.1.GA


import com.google.gwt.user.client.rpc.IsSerializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlValue;

/**
 * EntityAttribute generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.NONE)
public class EntityAttribute  implements java.io.Serializable, IsSerializable {

    private Long id;
	@XmlValue
    private String name;
    private String possibleValues;
    private String style;
    private String description;

    public EntityAttribute() {
    }

	
    public EntityAttribute(Long id) {
        this.id = id;
    }
    public EntityAttribute(Long id, String name, String possibleValues, String style, String description) {
       this.id = id;
       this.name = name;
       this.possibleValues = possibleValues;
       this.style = style;
       this.description = description;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPossibleValues() {
        return this.possibleValues;
    }
    
    public void setPossibleValues(String values) {
        this.possibleValues = values;
    }
    public String getStyle() {
        return this.style;
    }
    
    public void setStyle(String style) {
        this.style = style;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
}


