package org.janelia.it.jacs.model.entity;
// Generated May 26, 2011 10:42:23 AM by Hibernate Tools 3.2.1.GA


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlValue;

import com.google.gwt.user.client.rpc.IsSerializable;

/**
 * EntityStatus generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.NONE)
public class EntityStatus  implements java.io.Serializable, IsSerializable {
     
	private Long id;
    @XmlValue
    private String name;

    public EntityStatus() {
    }

    public EntityStatus(Long id) {
        this.id = id;
    }
    public EntityStatus(Long id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
}


