package org.janelia.it.jacs.model.entity;
// Generated May 26, 2011 10:42:23 AM by Hibernate Tools 3.2.1.GA


import com.google.gwt.user.client.rpc.IsSerializable;

/**
 * EntityTypeGenomic generated by hbm2java
 */
public class EntityType  implements java.io.Serializable, IsSerializable {
     private String id;
     private Long sequence;
     private String name;
     private String style;
     private String description;
     private String iconurl;

    public EntityType() {
    }

	
    public EntityType(String id) {
        this.id = id;
    }
    public EntityType(String id, Long sequence, String name, String style, String description, String iconurl) {
       this.id = id;
       this.sequence = sequence;
       this.name = name;
       this.style = style;
       this.description = description;
       this.iconurl = iconurl;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Long getSequence() {
        return this.sequence;
    }
    
    public void setSequence(Long sequence) {
        this.sequence = sequence;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStyle() {
        return this.style;
    }
    
    public void setStyle(String style) {
        this.style = style;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getIconurl() {
        return this.iconurl;
    }
    
    public void setIconurl(String iconurl) {
        this.iconurl = iconurl;
    }

}


