package org.janelia.it.jacs.model.entity;
// Generated May 26, 2011 10:42:23 AM by Hibernate Tools 3.2.1.GA


import com.google.gwt.user.client.rpc.IsSerializable;
import org.janelia.it.jacs.model.user_data.User;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Entity generated by hbm2java
 */
public class Entity  implements java.io.Serializable, IsSerializable {
     private String id;
     private User user;
     private EntityStatus entityStatus;
     private EntityType entityType;
     private Date creationDate;
     private Date updatedDate;
     private Set entityDatas = new HashSet(0);

    public Entity() {
    }

	
    public Entity(String id) {
        this.id = id;
    }
    public Entity(String id, User user, EntityStatus entityStatus, EntityType entityType, Date creationDate, Date updatedDate, Set entityDatas) {
       this.id = id;
       this.user = user;
       this.entityStatus = entityStatus;
       this.entityType = entityType;
       this.creationDate = creationDate;
       this.updatedDate = updatedDate;
       this.entityDatas = entityDatas;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public EntityStatus getEntityStatus() {
        return this.entityStatus;
    }
    
    public void setEntityStatus(EntityStatus entityStatus) {
        this.entityStatus = entityStatus;
    }
    public EntityType getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(EntityType entityType) {
        this.entityType = entityType;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public Set getEntityDatas() {
        return this.entityDatas;
    }
    
    public void setEntityDatas(Set entityDatas) {
        this.entityDatas = entityDatas;
    }




}


