package org.janelia.it.jacs.model.entity;
// Generated May 26, 2011 10:42:23 AM by Hibernate Tools 3.2.1.GA


import com.google.gwt.user.client.rpc.IsSerializable;

/**
 * EntityTypeAttribute generated by hbm2java
 */
public class EntityTypeAttribute  implements java.io.Serializable, IsSerializable {
     private Long id;
     private Long entityTypeId;
     private Long entityAttId;

    public EntityTypeAttribute() {
    }

    public EntityTypeAttribute(Long id) {
        this.id = id;
    }
    public EntityTypeAttribute(Long id, Long entityTypeId, Long entityAttId) {
       this.id = id;
       this.entityTypeId = entityTypeId;
       this.entityAttId = entityAttId;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getEntityTypeId() {
        return this.entityTypeId;
    }
    
    public void setEntityTypeId(Long entityTypeId) {
        this.entityTypeId = entityTypeId;
    }
    public Long getEntityAttId() {
        return this.entityAttId;
    }
    
    public void setEntityAttId(Long entityAttId) {
        this.entityAttId = entityAttId;
    }




}


