package org.janelia.it.jacs.model.entity;
// Generated May 26, 2011 10:42:23 AM by Hibernate Tools 3.2.1.GA


import com.google.gwt.user.client.rpc.IsSerializable;
import org.janelia.it.jacs.model.user_data.User;

import java.util.Date;

/**
 * EntityData generated by hbm2java
 */
public class EntityData implements java.io.Serializable, IsSerializable {
    private Long id;
    private EntityAttribute entityAttribute;
    private Entity parent_entity;
    private Entity child_entity;
    private User user;
    private String value;
    private Date creationDate;
    private Date updatedDate;
    private Integer orderIndex;

    public EntityData() {
    }

    public EntityData(Long id) {
        this.id = id;
    }

    public EntityData(Long id, EntityAttribute entityAttribute, Entity parent_entity, Entity child_entity, User user,
                      String value, Date creationDate, Date updatedDate, Integer orderIndex) {
        this.id = id;
        this.entityAttribute = entityAttribute;
        this.parent_entity = parent_entity;
        this.child_entity = child_entity;
        this.user = user;
        this.value = value;
        this.creationDate = creationDate;
        this.updatedDate = updatedDate;
        this.orderIndex = orderIndex;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public EntityAttribute getEntityAttribute() {
        return this.entityAttribute;
    }

    public void setEntityAttribute(EntityAttribute entityAttribute) {
        this.entityAttribute = entityAttribute;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }


    public Entity getParent_entity() {
        return parent_entity;
    }

    public void setParent_entity(Entity parent_entity) {
        this.parent_entity = parent_entity;
    }

    public Entity getChild_entity() {
        return child_entity;
    }

    public void setChild_entity(Entity child_entity) {
        this.child_entity = child_entity;
    }

    public Integer getOrderIndex() {
        return orderIndex;
    }

    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }
}


