package org.janelia.it.jacs.model.entity;
// Generated May 26, 2011 10:42:23 AM by Hibernate Tools 3.2.1.GA


import com.google.gwt.user.client.rpc.IsSerializable;
import org.janelia.it.jacs.model.user_data.User;

import javax.xml.bind.annotation.*;
import java.util.Date;

/**
 * EntityData generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class EntityData implements java.io.Serializable, IsSerializable {
	
	@XmlAttribute(name="guid")
    private Long id;

	@XmlElement
    private EntityAttribute entityAttribute;
	
    @XmlTransient
    private Entity parentEntity;

	@XmlElement
    private Entity childEntity;

	@XmlElement
    private User user;

	@XmlElement
    private String value;
	
    @XmlTransient
    private Date creationDate;
    
    @XmlTransient
    private Date updatedDate;

	@XmlElement
    private Integer orderIndex;

    public EntityData() {
    }

    public EntityData(Long id) {
        this.id = id;
    }

    public EntityData(Long id, EntityAttribute entityAttribute, Entity parentEntity, Entity childEntity, User user,
                      String value, Date creationDate, Date updatedDate, Integer orderIndex) {
        this.id = id;
        this.entityAttribute = entityAttribute;
        this.parentEntity = parentEntity;
        this.childEntity = childEntity;
        this.user = user;
        this.value = value;
        this.creationDate = creationDate;
        this.updatedDate = updatedDate;
        this.orderIndex = orderIndex;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public EntityAttribute getEntityAttribute() {
        return this.entityAttribute;
    }

    public void setEntityAttribute(EntityAttribute entityAttribute) {
        this.entityAttribute = entityAttribute;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }


    public Entity getParentEntity() {
        return parentEntity;
    }

    public void setParentEntity(Entity parentEntity) {
        this.parentEntity = parentEntity;
    }

    public Entity getChildEntity() {
        return childEntity;
    }

    public void setChildEntity(Entity childEntity) {
        this.childEntity = childEntity;
    }

    public Integer getOrderIndex() {
        return orderIndex;
    }

    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }
}


