package org.janelia.it.jacs.model.entity;
// Generated May 26, 2011 10:42:23 AM by Hibernate Tools 3.2.1.GA


import com.google.gwt.user.client.rpc.IsSerializable;

/**
 * EntityAttribute generated by hbm2java
 */
public class EntityAttribute  implements java.io.Serializable, IsSerializable {
     private String id;
     private String name;
     private String vals;
     private String style;
     private String description;

    public EntityAttribute() {
    }

	
    public EntityAttribute(String id) {
        this.id = id;
    }
    public EntityAttribute(String id, String name, String vals, String style, String description) {
       this.id = id;
       this.name = name;
       this.vals = vals;
       this.style = style;
       this.description = description;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getVals() {
        return this.vals;
    }
    
    public void setVals(String vals) {
        this.vals = vals;
    }
    public String getStyle() {
        return this.style;
    }
    
    public void setStyle(String style) {
        this.style = style;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
}


