
package org.janelia.it.jacs.model.download;

import com.google.gwt.user.client.rpc.IsSerializable;

import java.io.Serializable;
// Generated Nov 1, 2006 10:34:45 AM by Hibernate Tools 3.2.0.beta6a


/**
 * Author generated by hbm2java
 */
public class Author implements Serializable, IsSerializable {

    // Fields

    private String name;

    // Constructors

    /**
     * default constructor
     */
    public Author() {
    }

    /**
     * full constructor
     */
    public Author(String name) {
        this.name = name;
    }


    // Property accessors
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


}


