
package org.janelia.it.jacs.model.download;
// Generated Nov 1, 2006 11:42:33 AM by Hibernate Tools 3.2.0.beta6a


import com.google.gwt.user.client.rpc.IsSerializable;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Project generated by hbm2java
 */
public class Project implements Serializable, IsSerializable {

    // Fields

    private String name;
    private String symbol;
    private String description;
    private List<Publication> publications = new ArrayList<Publication>();
    private String principal_investigators;
    private String organization;
    private String email;
    private String website_url;
    private Boolean released;
    private String funded_by;
    private String institutional_affiliation;

    // Constructors

    /**
     * default constructor
     */
    public Project() {
    }

    /**
     * minimal constructor
     */
    public Project(String symbol) {
        this.symbol = symbol;
    }

    /**
     * full constructor
     */
    public Project(String symbol, String description, List<Publication> publications) {
        this.symbol = symbol;
        this.description = description;
        this.publications = publications;
    }


    // Property accessors
    public String getSymbol() {
        return this.symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<Publication> getPublications() {
        return this.publications;
    }

    public void setPublications(List<Publication> publications) {
        this.publications = publications;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getOrganization() {
        return organization;
    }

    public void setOrganization(String organization) {
        this.organization = organization;
    }

    public String getPrincipal_investigators() {
        return principal_investigators;
    }

    public void setPrincipal_investigators(String principal_investigators) {
        this.principal_investigators = principal_investigators;
    }

    public String getWebsite_url() {
        return website_url;
    }

    public void setWebsite_url(String website_url) {
        this.website_url = website_url;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getReleased() {
        return released;
    }

    public void setReleased(Boolean released) {
        this.released = released;
    }

    public String getFunded_by() {
        return funded_by;
    }

    public void setFunded_by(String funded_by) {
        this.funded_by = funded_by;
    }

    public String getInstitutional_affiliation() {
        return institutional_affiliation;
    }

    public void setInstitutional_affiliation(String institutional_affiliation) {
        this.institutional_affiliation = institutional_affiliation;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null) return false;

        final Project project = (Project) o;

        return !(symbol != null ? !symbol.equals(project.symbol) : project.symbol != null);

    }

    public int hashCode() {
        return (symbol != null ? symbol.hashCode() : 0);
    }

    public String toString() {
        StringBuffer sb = new StringBuffer("");
        sb.append("name=").append(name).append("\n");
        sb.append("symbol=").append(symbol).append("\n");
        sb.append("description=").append(description).append("\n");
        sb.append("principal investigators=").append(principal_investigators).append("\n");
        sb.append("organization=").append(organization).append("\n");
        sb.append("websiteUrl=").append(website_url).append("\n");
        sb.append("released=").append(released).append("\n");
        sb.append("funded by=").append(funded_by).append("\n");
        sb.append("institutional affiliation=").append(institutional_affiliation).append("\n");
        if (publications == null) {
            sb.append("publications=null");
        }
        else {
            sb.append("publications=").append(publications.size());
        }
        return sb.toString();
    }
}


